repos:
  - repo: local
    hooks:
      - id: pretty-xml
        name: Pretty print XML files
        entry: python .git-hooks/pretty_xml.py
        language: system
        files: \.xml$

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: '.*\.xml' # xml files are controlled through ArcPro metadata editor
