contact_links:
    - name: Ask questions from the GEE community
      url: https://gis.stackexchange.com/questions/tagged/google-earth-engine
      about: To get answers from questions in the GEE commminuty, please ask and answer questions here.