name: release-please
on:
  push:
    branches:
      - main  # Use your default branch

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: python  # Change to node/go/java if needed
          package-name: my-package
